---
title: "Quiz6"
author: "Zihan Ma"
date: "2023-02-20"
output: html_document
---


```{r libraries data, message=FALSE, warning=FALSE}
# Libraries used in this markdown
library(rmarkdown)
library(readxl)
library(readr)
library(tidyverse)
library(dplyr)
library(knitr)
library(kableExtra)
library(magrittr)
library(RColorBrewer)
library(gtools)
# Data imported from M2Project_Data.xlsx
library(readxl)
M2Data <- read_excel("DataSets/M2Project_Data-1.xlsx", 
    sheet = "M2Project_V2")
```


```{r}
n = 156
mean = 65
stdev = 3

(71-mean)/stdev 
71-mean/stdev
```

```{r}
attach(mtcars)
plot(disp, mpg)
detach(mtcars)



attach(mtcars)
plot(mpg, disp)
detach(mtcars)

attach(mtcars)
plot(mpg, disp, col = 'blue')
detach(mtcars)
```
```{r}
zscore220 = (220-mean)/stdev
zscore228 = (228-mean)/stdev

# Calculate the area below each Z score
area_below_zscore220 = pnorm(zscore220)
area_below_zscore228 = pnorm(zscore228)

# Subtract the smallest area from the bigger one
area_below_zscore228
area_below_zscore220



# Probability = 7.79%
```
```{r}
zscore220 = (220-mean)/stdev
zscore228 = (228-mean)/stdev

# Calculate the area below each Z score
area_below_zscore220 = 1-pnorm(zscore220)
area_below_zscore228 = 1-pnorm(zscore228)

# Subtract the smallest area from the bigger one
area_below_zscore228
area_below_zscore220



# Probability = 7.79%
```
```{r}
mean = 200
stdev = 20

# First, calculate z scores for each value

zscore180 = (180-mean)/stdev
zscore160 = (160-mean)/stdev

# Subtract the Z scores

zscore180 - zscore160
```

```{r}
mean = 200
stdev = 20

# First, calculate z scores for each value

zscore180 = (180-mean)/stdev
zscore160 = (160-mean)/stdev

# Calculate the area below each Z score

area_below_zscore180 = pnorm(zscore180)
area_below_zscore160 = pnorm(zscore160)

# Subtract the areas

area_below_zscore160 - area_below_zscore180

```

```{r}
mean = 200
stdev = 20

# First, calculate z scores for each value

zscore180 = (180-mean)/stdev
zscore160 = (160-mean)/stdev

# Calculate the area below each Z score

area_below_zscore180 = pnorm(zscore180)
area_below_zscore160 = pnorm(zscore160)

# Subtract the smallest area from the bigger one

area_below_zscore180 - area_below_zscore160

```
```{r}
zscore = (83-mean)/stdev
print(paste(round(zscore,2)), quote = F)


zscore = (83-mean)/stdev
print(paste(round(zscore,2)), quote = F)


zscore = (83-mean)/stdev
print(paste(round(zscore,2)), quote = F)


zscore = (83-mean)/stdev
print(paste(round(zscore,2)), quote = F)

```

```{r}
sd1 = 22

sd2 = 25

n1 = 2

n2 = 4

sqrt((sd1^2/n1) + (sd2^2/n2))
sqrt((sd1^2/n1)+(sd2^2/n2))
sqrt(sd1^2/n1 + sd2^2/n2)
```

```{r}
sample_2 = c(1,2,3,4,5)
permutations(n=5,r=3,v=sample_2,repeats.allowed=T)
```

```{r}


set3 = c(1,52,52,53,54,54,54,56,56,57,57,59,59,59,60,60,62,62,63,
64,65,66,66,67,68,69,69,70,70,71,72,72,73,75,76,76,77,77,78,78,
78,79,79,79,79,81,81,82,83,85,91,92,92,94,96,97,98,98,99,101,
101,102,103,103,104,106,106,108,109,109,109,110,110,111,111,
111,112,113,114,115,116,117,117,119,119,120,120,120,121,122,
123,123,124,125,332,430)






boxplot.stats(set3)



```

```{r}
datasets::cars

dplyr::mutate(datasets::cars,ratio=dist/speed)

```

<FONT COLOR="red"><B>WORD</B></FONT>

or

<FONT STYLE="color:red; font-weight:bold;">WORD</FONT>


<FONT RED><B>WORD</B></FONT>

<FONT SIZE = 3, color="red">WORD</FONT>

<COLOR="red"><B>WORD</B></COLOR>

<FONT SIZE = 3, color="red"><B>WORD</B></FONT>

<FONT SIZE = 3, color="red"><Bold>WORD</B></FONT>


```{r}
table(ChickWeight$Diet)

```

































